# Generated by Django 4.0.6 on 2022-07-14 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=97, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=29, unique=True)),
                ('secret', models.UUIDField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('verified', models.BooleanField(default=False)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to='asome.topic')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='asome.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date submitted')),
                ('content', models.CharField(max_length=1024)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='asome.user')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='asome.topic')),
            ],
        ),
    ]
