# Generated by Django 4.0.6 on 2022-07-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=97, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='asome.topic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='asome.topic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=29, unique=True),
        ),
    ]
