# Generated by Django 4.0.6 on 2022-07-14 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asome', '0002_alter_topic_name_alter_user_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='asome.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='asome.topic'),
        ),
    ]
